testing 9009

diff --git a/scripts/pre-push-ubuntu b/scripts/pre-push-ubuntu
--- a/scripts/pre-push-ubuntu
+++ b/scripts/pre-push-ubuntu
@@ -13,18 +13,14 @@ fi
 # Ensure Gradle execution from the root project
 cd "$(git rev-parse --show-toplevel)"
 
-# Iterate through changed files and check them individually
-for file in $CHANGED_FILES
-do
-    echo "Checking Ktlint for file: $file"
-    ./gradlew ktlintCheck
+# Run Ktlint check only for changed files
+./gradlew ktlintCheck --files $(echo "$CHANGED_FILES" | tr '\n' ',')
 
-    # Check the exit status of the Ktlint check
-    if [ $? -ne 0 ]; then
-        echo "Ktlint check failed on file: $file"
-        exit 1
-    fi
-done
+# Check the exit status of the Ktlint check
+if [ $? -ne 0 ]; then
+    echo "Ktlint check failed on some files."
+    exit 1
+fi
 
 echo "Ktlint check passed on all changed files."
 exit 0
