set comit

diff --git a/scripts/pre-push-window b/scripts/pre-push-window
--- a/scripts/pre-push-window
+++ b/scripts/pre-push-window
@@ -1,7 +1,6 @@
 #!/bin/bash
 ##  < #!C:/Program\ Files/Git/usr/bin/sh.exe >  ##
 
-
 # Retrieve changed Kotlin files from the recent commit
 CHANGED_FILES=$(git diff --name-only HEAD~1 -- '*.kt')
 echo "Changed files are: $CHANGED_FILES"
@@ -12,21 +11,24 @@ if [ -z "$CHANGED_FILES" ]; then
     exit 0
 fi
 
-# Ensure Gradle execution from the root project
-cd "$(git rev-parse --show-toplevel)"
-
-# Iterate through changed files and check them individually
-for file in $CHANGED_FILES
-do
-    echo "Checking Ktlint for file: $file"
-    ./gradlew.bat ktlintCheck --project-dir=$(dirname "$file")
-
-    # Check the exit status of the Ktlint check
-    if [ $? -ne 0 ]; then
-        echo "Ktlint check failed on file: $file"
+# Check if ktlint binary exists in the project directory
+KTLINT_BINARY="./ktlint"
+if [ ! -e "$KTLINT_BINARY" ]; then
+    # Check if ktlint is available in the system path
+    if command -v ktlint &>/dev/null; then
+        KTLINT_BINARY="ktlint"
+    else
+        echo "Ktlint not found. Please install Ktlint on your system or include it in the project directory."
         exit 1
     fi
-done
+fi
+
+# Run Ktlint check only for changed files
+echo "$CHANGED_FILES" | xargs "$KTLINT_BINARY" --relative
+if [ $? -ne 0 ]; then
+    echo "Ktlint check failed on some files."
+    exit 1
+fi
 
 echo "Ktlint check passed on all changed files."
 exit 0
